// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"

import (
	"html/template"
)

var StyleTemplate = template.Must(template.New("example").Parse("<style>{{ . }}</style>"))

func EscapedCssComponent(content string) templ.Component {
	return templ.FromGoHTML(StyleTemplate, template.CSS(templ.EscapeString(content)))
}
